### ISSUE TITLE
Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

### ISSUE THREAD

**Issue by ducomin** [skandasoft/browser-plus#98]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.67

### Stack Trace

Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

```
At module.js:340

Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/ducomin/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (/home/ducomin/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (/home/ducomin/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app.asar/src/view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.itemRemoved (/usr/share/atom/resources/app.asar/src/pane-element.js:180:37)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:568:20)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.closeTab (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:321:26)
    at Object.addElementCommands.tabs:close-tab (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:95:26)
    at atom-tabs.commandsWithPropagationStopped.(anonymous function) (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:86:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:340:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
  3x -4:25.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:44 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:11.7.0 core:paste (atom-text-editor.editor.mini.is-focused)
  4x -0:32.5.0 core:cancel (atom-pane.pane.active)
     -0:16.9.0 browser-plus:open (atom-text-editor.editor.is-focused)
     -0:05.1.0 core:cancel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.seti-ui-no-icons)
     -0:01.0 tabs:close-tab (li.tab.sortable.right-clicked)
```

### Config

```json
{
  "browser-plus": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
browser-plus, v0.0.67
color-picker, v2.2.2
emmet, v2.4.3
file-icons, v1.7.17
highlight-selected, v0.11.2

# Dev
No dev packages
```

**Comment by hsavit1** [comment]
just install browser plus and am experiencing this as well

**Comment by Akumetsu-Dev** [comment]
on windows 10 the same Error.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.67


### Stack Trace

Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

```
At module.js:340

Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Walddys Emmanuel/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (file:///C:/Users/Walddys Emmanuel/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (file:///C:/Users/Walddys Emmanuel/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:86:21)
    at atom-pane.PaneElement.itemRemoved (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:180:37)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.removeItem (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:568:20)
    at Pane.module.exports.Pane.destroyItem (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:637:16)
    at atom-tabs.TabBarView.onClick (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:688:17)
```

### Commands

```
     -0:24.1.0 command-palette:toggle (atom-text-editor.editor.power-mode.is-focused)
     -0:21 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:20.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.4.0 browser-plus:open (atom-text-editor.editor.power-mode)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
autoclose-html, v0.23.0
browser-plus, v0.0.67
browser-plus-zoom, v0.0.1
double-tag, v0.2.0
file-icons, v1.7.17
language-matlab, v0.2.1
minimap, v4.24.7
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
navigate, v0.1.16
pp, v0.0.1
preview-plus, v1.2.7
tag, v0.4.0

# Dev
No dev packages
```

**Comment by asdrubalivan** [comment]
I'm experiencing the same, using Fedora 23 on a fresh install

**Comment by Lucas-Geitner** [comment]
Same

**Comment by adamorvek** [comment]
Same here

**Comment by jennuine** [comment]
The latest update still produces the same error:

Uncaught Error: Cannot find module '../node_modules/jquery-ui/autocomplete.js'

**Comment by MoPHL** [comment]
I still experience this as well.

**Comment by jennuine** [comment]
I've referenced a quick fix in #94 that still works after the update

**Comment by skandasoft** [comment]
did you try the latest patch.

**Comment by jennuine** [comment]
Yes, I updated to 0.0.74 and still receive the error

**Comment by mhnavarro** [comment]
@skandasoft jquery-autocomplete package should be referenced on `package.json`, no?

**Comment by mikesprague** [comment]
Any news on this? I've uninstalled and reinstalled browser-plus several times, am on the newest release (0.0.76) and still receive this error.

**Comment by skandasoft** [comment]
I wish some body could help with this..because it is not happening on my m/c and it is as simple as file dependency and it is there in https://github.com/skandasoft/browser-plus/tree/master/node_modules/jquery-ui .

**Comment by mikesprague** [comment]
Is there any additional information I could give you that would help? I did a global install of jquery-ui via npm too (figured it was worth a shot) but it didn't help. I am on the newest beta of Atom (1.10.0-beta7) if that matters.

**Comment by jennuine** [comment]
In terminal, have you run `apm rebuild-module-cache`? I updated browser-plus on another computer and it would not open correctly. After exiting atom, running the command, and re-opening the project it worked fine

**Comment by mikesprague** [comment]
I hadn't thought to do that @jennuine. When I tried running that command it repeatedly failed with the error `Cannot read property 'link' of undefined` on the first package.

**Comment by jennuine** [comment]
It sounds like something wrong with your atom installation.. Have you updated it? Also, try running `apm rebuild`.

If it continues to fail, you'll probably have to uninstall then reinstall atom

**Comment by mikesprague** [comment]
I use the portable version of atom so each new beta I remove everything and add a fresh copy. Last time I installed was about 4 days ago. This issue has persisted between the last several installs.

I have also run `apm rebuild` a couple times - that works without issue.  I'm probably going to give up on this since it's the only package not working. 

Thanks for your help @jennuine.

**Comment by jayjun** [comment]
I fixed it by copying `node_modules/jquery-ui` from the repo directly into `/Users/<redacted>/.atom/packages/browser-plus/node_modules`.

For some reason, the `jquery-ui` folder is missing when installing browser-plus from the Package Manager.

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.76

**Comment by mikesprague** [comment]
That did it, it's working again! Thanks so much @jayjun 👍

**Comment by mikesprague** [comment]
@skandasoft The above fixed it for me. Do you think adding jQuery UI to the dependencies in package.json would make any difference for other still having the problem?

**Comment by cpitkin** [comment]
I am having the same issue. After reading over the thread I added `"jquery-ui": "^1.12.0"` to package.json then ran `npm install`. That did not work. I was able to successfully get it working by simply cloning the repo into `~/.atom/packages/` then running `cd browser-plus && npm install`. I hope that helps.

**Comment by skandasoft** [comment]
thanks @cpitkin @jennuine @jayjun @mikesprague . Closing the issue.

**Comment by mccolljr** [comment]
I ran into this issue just today, and I was able to fix it using the methods suggested within. Just leaving this here in case anyone stumbles upon it like I did.
